config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/proyectos', to: 'projects#index', as: 'proyectos'
  get '/contacto', to: 'contact#index', as: 'contacto'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
      # Código para la acción index (página de contacto)
    end
end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      # Código para la acción index (página de inicio)
    end
end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      # Código para la acción index (página de proyectos)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacto</title>
</head>
<body>
  <%= render partial: 'layouts/menu' %>
  <h1 class="text-center pt-4">Contactame</h1>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form class="form-contacto">
          <div class="mb-3 formulario">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="nombre">
            <label for="correo" class="form-label">Correo electrónico</label>
            <input type="email" class="form-control" id="correo" aria-describedby="emailHelp">
            <label for="asunto" class="form-label">Asunto</label>
            <input type="text" class="form-control" id="asunto">
            <label for="mensaje" class="form-label">Mensaje</label>
            <textarea type="text" class="form-control" rows="7" id="mensaje"></textarea>
          </div>
          <button type="submit" class="btn">Enviar</button>
        </form>
      </div>
    </div>
  </div>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inicio</title>
</head>
<body>
  <%= render partial: 'layouts/menu' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col" style="padding: 0;">
        <%= image_tag "banner.jpg", id:'banner', alt: "Programando"%>
      </div>
    </div>
  </div>
  <div class="container-fluid pt-5">
    <div class="row">
      <div class="col">
        <h1 class="text-center">Bievenido a mi portafolio</h1>
        <p class="text-center mx-5 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vestibulum est quis quam placerat, ac consequat tellus lacinia. Quisque sit amet aliquam leo. Vivamus a metus sagittis, maximus odio ut, porta enim. Phasellus pharetra nulla a risus pellentesque, non sollicitudin ipsum tempus. Nam tristique elementum quam id iaculis. Etiam scelerisque felis eu tortor consectetur, non ultrices nulla ultricies. Nullam luctus auctor rutrum.</p>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <p class="pt-3">Humberto Martinez<p>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link active text-white", "aria-current": "page" %>
        </li>
        <li class="nav-item">
          <%= link_to "Proyectos", proyectos_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contacto", contacto_path, class: "nav-link text-white" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyectos</title>
</head>
<body>
  <%= render partial: 'layouts/menu' %>
  <h1 class="text-center pt-4">Mis proyectos</h1>
  <div class="container d-flex justify-content-center pt-4">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-4 w-100" style="width: 18rem;">
          <%= image_tag "cuppon.jpg", class:'card-img-top', alt: "captura de cuppon"%>
          <div class="card-body">
            <h5 class="card-title">CUPPON</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
            <a href="#" class="btn">Ver más</a>
          </div>
        </div>
        <div class="card mb-4 w-100" style="width: 18rem;">
          <%= image_tag "iguana-page.jpg", class:'card-img-top', alt: "captura de iguana page"%>
          <div class="card-body">
            <h5 class="card-title">IGUANA PAGE</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
            <a href="#" class="btn">Ver más</a>
          </div>
        </div>
        <div class="card mb-4 w-100" style="width: 18rem;">
          <%= image_tag "suricata.jpg", class:'card-img-top', alt: "captura de suricata"%>
          <div class="card-body">
            <h5 class="card-title">SURICATA</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
            <a href="#" class="btn">Ver más</a>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card mb-4 w-100" style="width: 18rem;">
          <%= image_tag "viajes-chile.jpg", class:'card-img-top', alt: "captura de viajes Chile"%>
          <div class="card-body">
            <h5 class="card-title">VIAJES CHILE</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
            <a href="#" class="btn">Ver más</a>
          </div>
        </div>
        <div class="card mb-4 w-100" style="width: 18rem;">
          <%= image_tag "ricomida.jpg", class:'card-img-top', alt: "captura de Ricomida"%>
          <div class="card-body">
            <h5 class="card-title">RICOMIDA</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
            <a href="#" class="btn">Ver más</a>
          </div>
        </div>
        <div class="card mb-4 w-100" style="width: 18rem;">
          <%= image_tag "olivia-ros.jpg", class:'card-img-top', alt: "captura de Olivia Ros"%>
          <div class="card-body">
            <h5 class="card-title">OLIVIA ROS</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
            <a href="#" class="btn">Ver más</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>